#!/bin/bash

# setup: Set up application for the first time after cloning, or set it back to the initial state.
#

# Drop out if one of the commands fails
set -e

# Ensure we are working from the top of the project
cd "$(dirname "$0")/.."

# Run bootstrap script to resolve dependencies
script/bin/bootstrap

# Reset database to a fresh state
# echo
# echo "==> Setting up DB…"
# echo

echo
echo "==> App is now ready to go!"
echo
