#!/bin/bash

# test: Run test suite for project. Optionally run an individual test(s).
#

# Drop out if one of the commands fails
set -e

echo
echo "==> Start running tests at $(date "+%H:%M:%S")"

# Work out path to script folder
script_path=$(dirname "$0")

# Check if arguments are passed allowing call to specific test(s).
# As an example this calls a simple script to check these shell scripts are valid.
if [[ -n $1 ]]
then
  "$script_path/bin/check_scripts" "$@"
else
  "$script_path/bin/check_scripts"
fi

echo
echo "==> Tests finished at $(date "+%H:%M:%S")"
echo
