#!/bin/bash

# update: Update application to run for its current checkout.
#

# Drop out if one of the commands fails
set -e

echo
echo "==> Ensuring everything is up to date for this project…"

# Ensure we are working from the top of the project
cd "$(dirname "$0")/.."
echo "Change directory to: $(pwd)"

# Run bootstrap script to resolve dependencies
script/bin/bootstrap

# Run all database migrations to ensure everything is up to date.
# echo
# echo "==> Updating db…"
# echo

echo
echo "==> You are now ready to go!"
echo
